sonar.projectKey=mathapi
sonar.projectName=mathapi
sonar.projectVersion=1.0.0
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.js
sonar.exclusions=node_modules/**,coverage/**,dependency-check-report/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
